""" numpy """

In [1]:
# 1. Ստեղծել np զանգված, որը կպարունակի 100 պատահական ամբողջ թիվ։ Այնուհետև ստանալ այն տարրերի ինդեքսները,
# որոնք ավարտվում են 6-ով։

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0,100, size=(100,))
index = np.where(arr % 10 == 6)

print(arr)
print('_'*65)
print(index)

[89 94 17  6 26 18 56 46 48 20 24 48 72 51 82  7 11 92  3 66 54 68 45 25
 28 24 47 79 83 10 98 12  0 74 47 41 89 13 98 87 82 92 61 12 21 35 18 11
  9 56 35  5 23 90 15  8 13  2 82 76 75 84 13 44 25 13 59 80 11 76 33 48
 70 40 76 48 16 51 70 35 87 25 78 23  8  2 36 59 62 71 34 69 21 27 73 75
 80 69 34 36]
_________________________________________________________________
(array([ 3,  4,  6,  7, 19, 49, 59, 69, 74, 76, 86, 99], dtype=int64),)


In [4]:
# 2. Ստեղծել np զանգված, որի բոլոր տարրերը կլինեն 0-ներ, իսկ անկյունագծայինները՝ 1։

In [5]:
zeros = np.zeros(shape=(4,4))
np.fill_diagonal(zeros,1)

print(zeros.astype(int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [6]:
# 3. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից։ Ապա կցեք երկու զանգվածներն իրար
# հորիզոնական ուղությամբ։

In [7]:
l = [1,2,3,4,5,6]
l1 = [6,7,8,9,10,11]

arr = np.array(l)
arr1 = np.array(l1)

print(np.hstack((arr,arr1)))

[ 1  2  3  4  5  6  6  7  8  9 10 11]


In [8]:
# 4. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից։ Ապա կցեք երկու
# զանգվածներն իրար վերտիկալ ուղությամբ։

In [9]:
print(np.vstack((arr,arr1)))

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]


In [10]:
# 5. Ստեղծել երկչափ զանգված, որը կունենա (3, 3) shape: Այնուհետև ստեղծել նոր զանգված, որը կլինի նախորդ զանգվածը, սակայն
# առաջին և երրորդ սյուների տեղերը փոխած։

In [11]:
arr1 = np.random.randint(1,10, size=(3,3))
temp = arr1.copy()
temp[:,0],temp[:,2] = arr1[:,2],arr1[:,0]

print(arr1)
print('_'*15)
print(temp)

[[5 3 1]
 [3 8 1]
 [7 6 9]]
_______________
[[1 3 5]
 [1 8 3]
 [9 6 7]]


In [12]:
# 6.  Ստեղծել երեք զանգված։ Առաջինը պետք է պարունակի միայն 0-ներ, երկրորդը միայն 1-եր, իսկ երրորդը միայն 9-եր։

In [13]:
zeros = np.zeros(shape=(4,4))
ones = np.ones(shape=(4,4))
nine = np.empty(shape=(4,4))
nine.fill(9)

print(zeros)
print('_'*15)
print(ones)
print('_'*15)
print(nine)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
_______________
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
_______________
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [14]:
# 7. Ստեղծել (10, 10) shape-ով զանգված։ Ապա փոխել դրա shape-ը հնարավոր բոլոր տարբերակներով։

In [15]:
a = np.random.randint(0,100,size=(10,10))
print(a)
print('_'*65)
print(a.reshape(5,20))
print('_'*65)
print(a.reshape(20,5))
print('_'*65)
print(a.reshape(100,1))
print('_'*65)
print(a.reshape(1,100))
print('_'*65)
print(a.reshape(25,4))
print('_'*65)
print(a.reshape(4,25))
print('_'*65)
print(a.reshape(50,2))
print('_'*65)
print(a.reshape(2,50))

[[84 43 31  1 59 25 12 11 58 82]
 [ 5  2  9  1 83 93 87 15 75 79]
 [84 51 10 64 64 74 37 74 64 26]
 [64  4 71 20 76 62  1 75 77 43]
 [ 1 63 36 33 64 22 42 22 70 61]
 [24 71 68 34 60 55 62 10 39 29]
 [ 2 39  5  8 98 48  7 64 92 56]
 [41 91 78 89 73 73 43 27 64 10]
 [ 8 48  8 83 71  3 52 36 83 20]
 [56 74 72 24  5 58 33 21 11 28]]
_________________________________________________________________
[[84 43 31  1 59 25 12 11 58 82  5  2  9  1 83 93 87 15 75 79]
 [84 51 10 64 64 74 37 74 64 26 64  4 71 20 76 62  1 75 77 43]
 [ 1 63 36 33 64 22 42 22 70 61 24 71 68 34 60 55 62 10 39 29]
 [ 2 39  5  8 98 48  7 64 92 56 41 91 78 89 73 73 43 27 64 10]
 [ 8 48  8 83 71  3 52 36 83 20 56 74 72 24  5 58 33 21 11 28]]
_________________________________________________________________
[[84 43 31  1 59]
 [25 12 11 58 82]
 [ 5  2  9  1 83]
 [93 87 15 75 79]
 [84 51 10 64 64]
 [74 37 74 64 26]
 [64  4 71 20 76]
 [62  1 75 77 43]
 [ 1 63 36 33 64]
 [22 42 22 70 61]
 [24 71 68 34 60]
 [55 62 10 39 29]
 [ 2 

In [16]:
# 8. Ստեղծել երկու երկչափ զանգված և հաշվել դրանց ա) տարր առ տարր արտադրյալը, բ) մատրիցային արտադրյալը։

In [17]:
a = np.random.randint(0,100,size=(4,4))
b = np.random.randint(0,100,size=(4,4))
print(a*b)
print('_'*30)
print(a@b)

[[2112 3528  324 1230]
 [2242 4028 2600 1608]
 [4774 2275 5194 3479]
 [ 470   87 5120  410]]
______________________________
[[10059  8041  8784  9332]
 [13061 10297 11120 12228]
 [16411 12981 12736 14396]
 [ 6925  5179  5302  5950]]


In [18]:
# 9. Ստեղծել երկու զանգված (10, 10) shape-ի, որոնք կպարունակեն 0-ից 20-ը պատահական թվեր։ Բաժանել մատրիցներն իրար։
# Այնուհետև առանձնացնել նոր մատրիցի մեջ մատրիցների այն տարրերը, որոնք թիվ են (inf կամ nan չեն): Ստանալ inf-երի և
# nan-երի նաև դրանց ինդեքսները։

In [7]:
arr = np.random.randint(0,20,size=(10,10))
arr1 = np.random.randint(0,20,size=(10,10))
arr2 = arr/arr1
arr3 = arr2[~(np.isnan(arr2))]
arr4 = arr3[~(np.isinf(arr3))]
index = np.where((np.isinf(arr2)) | (np.isnan(arr2)))
print(arr2)
print('_'*80)
print(arr4)
print('_'*80)
print(index)

[[ 0.28571429  1.45454545  1.33333333  0.          1.28571429  8.5
   2.4         1.          2.125       0.08333333]
 [ 1.75        1.4        15.          0.88888889         inf  0.11111111
   0.21428571  0.09090909  0.6         1.        ]
 [ 1.27272727  5.                 nan  0.28571429  0.36363636  7.5
   1.08333333  6.5         1.16666667  0.66666667]
 [ 0.          3.33333333  2.28571429  4.          1.05882353  6.
   0.9         3.66666667  0.05555556  1.42857143]
 [        inf  3.          5.33333333  1.54545455  1.6         0.92857143
   2.57142857  6.5         0.35294118  1.        ]
 [ 0.76923077         inf  1.          1.11764706  7.          0.42105263
   0.11111111 19.          0.33333333  4.33333333]
 [ 3.8         1.625       2.          1.25        1.33333333  0.90909091
   1.6         1.25        1.          0.35294118]
 [ 1.          1.72727273  0.76470588  0.4         0.8         0.
   0.47058824  0.3         1.0625      1.8       ]
 [ 0.88888889  0.88888889  0.0

<ipython-input-7-e13404a794f1>:3: RuntimeWarning: divide by zero encountered in true_divide
  arr2 = arr/arr1
<ipython-input-7-e13404a794f1>:3: RuntimeWarning: invalid value encountered in true_divide
  arr2 = arr/arr1


In [20]:
# 10. Ստեղծել (3, 3) մատրից, որի տարրերը կլինեն 11-19, սակայն բացահայտ կերպով սահմանել տարրերի տիպը որպես float։

In [21]:
arr = np.arange(11,20,dtype=float).reshape(3,3)
print(arr)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


""" numpy Part 2 """

In [22]:
# 1. Create a numpy array from a python list consisting even numbers from 0-20.
# 0-20 զույգ թվերը պարունակող Python լիստից ստեղծել զանգված։

In [23]:
l = list(range(0,21,2))
arr = np.array(l)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [24]:
# 2. Create a 3x3 numpy array, which will contain 3s only.
# Ստեղծել 3x3 զանգված, որը կպարունակի միայն 3-ներ:

In [25]:
arr = np.zeros(shape=(3,3))
arr.fill(3)
print(arr)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [26]:
# 3. Create a 1D numpy array with length 18. Reshape it to 3 columns and 6 rows.
# Ստեղծել միաչափ զանգված 18 երկկարությամբ։ Ապա այն դարձնել երկչափ զանգված, որը կունենա 3 սյուն և 6 տող։

In [27]:
arr1 = np.random.randint(0,10,size=(18,))
print(arr1)
arr1.shape = (6,3)
print(arr1)

[5 0 0 1 6 6 1 8 0 7 8 9 9 7 3 8 1 3]
[[5 0 0]
 [1 6 6]
 [1 8 0]
 [7 8 9]
 [9 7 3]
 [8 1 3]]


In [28]:
# 4. Create two numpy arrays of shape 10x10. One of them must contain the numbers from 1-100, the other from 100-1.
# Add them and output the result.
# Ստեղծել 10x10 երկու զանգված, որոնցից մեկը կպարունակի 1-100 թվերը, իսկ մյուսը՝ 100-1։ Գումարել դրանք և վերադարձնել
# արդյունքը։

In [29]:
arr1 = np.arange(1,101).reshape(10,10)
arr2 = np.arange(100,0,-1).reshape(10,10)
print(arr1)
print('_'*45)
print(arr2)
print('_'*45)
print(arr1+arr2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
_____________________________________________
[[100  99  98  97  96  95  94  93  92  91]
 [ 90  89  88  87  86  85  84  83  82  81]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 70  69  68  67  66  65  64  63  62  61]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 50  49  48  47  46  45  44  43  42  41]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 30  29  28  27  26  25  24  23  22  21]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 10   9   8   7   6   5   4   3   2   1]]
_____________________________________________
[[101 101 101 101 101 101 101 101 101 101]
 [1

In [30]:
# 5. In how many ways can we reshape an array of length 12? Write down all the possibilities (2D).
# Քանի՞ ձևով կարող ենք 12 երկարությամբ զանգվածի կառուցվածքը փոխել (reshape)։ Գրել բոլոր հնարավոր (2D) տարբերակները։

In [3]:
arr = np.random.randint(0,10,size=(12,))
print(arr)
print('_'*45)
print(arr.reshape(12,1))
print('_'*45)
print(arr.reshape(1,12))
print('_'*45)
print(arr.reshape(3,4))
print('_'*45)
print(arr.reshape(4,3))
print('_'*45)
print(arr.reshape(6,2))
print('_'*45)
print(arr.reshape(2,6))

[7 0 2 4 6 6 9 1 1 6 3 9]
_____________________________________________
[[7]
 [0]
 [2]
 [4]
 [6]
 [6]
 [9]
 [1]
 [1]
 [6]
 [3]
 [9]]
_____________________________________________
[[7 0 2 4 6 6 9 1 1 6 3 9]]
_____________________________________________
[[7 0 2 4]
 [6 6 9 1]
 [1 6 3 9]]
_____________________________________________
[[7 0 2]
 [4 6 6]
 [9 1 1]
 [6 3 9]]
_____________________________________________
[[7 0]
 [2 4]
 [6 6]
 [9 1]
 [1 6]
 [3 9]]
_____________________________________________
[[7 0 2 4 6 6]
 [9 1 1 6 3 9]]


In [32]:
# 6. Create an array of shape (5, 5) that will contain zeros except for the diagonal. The diagonal should be all 4s.
# Ստեղծել 5x5 զանգված, որը կպարունակի 0-ներ բացառությամբ անկյունագծից։ Անկյունագծի տարրերը պետք է լինեն 4։

In [33]:
zeros = np.zeros(shape=(5,5))
np.fill_diagonal(zeros,4)
print(zeros.astype(int))

[[4 0 0 0 0]
 [0 4 0 0 0]
 [0 0 4 0 0]
 [0 0 0 4 0]
 [0 0 0 0 4]]


In [34]:
# 7․ Create a numpy array that will contain random numbers from 0, 100 and will have 20 columns with 5 rows.
# Ստեղծել 0-100 պատահական թվերից կազմված զանգված, որը կունենա 5 տող և 20 սյուն։

In [35]:
arr = np.random.randint(0,100,size=(5,20))
print(arr)

[[53 58 87  5 33 58 18 43 21 91 98 45 45 20 22 78 15 97 38 59]
 [36 18 44 41 72 80 42 90 78 27 10 46 54  8 44 98 75  2 28 33]
 [79 61 63 78 37 90 60 36 27 32 74 24 85 50 65 63  6 68 12  3]
 [81 97  3 29 80 49 74 99  7 11 33 59 11 87  7  8 55 61  6 42]
 [76  1 90 29 22  1 52 46 67 40 85 65 64 81 59 76  1  0 54 94]]


In [36]:
# 8․ Create a 3 dimensional array from a 1 dimensional array of length 100.
# Ստեղծել եռաչափ զանգված 100 տարր պարունակող միաչափ զանգվածից։

In [37]:
arr = np.random.randint(0,100,size=(100,))
arr1 = arr.reshape(25,2,2)
print(arr1)

[[[21 25]
  [13 16]]

 [[13 76]
  [93 60]]

 [[70  0]
  [38 70]]

 [[66  3]
  [ 6 67]]

 [[70 49]
  [54 19]]

 [[95 33]
  [89 49]]

 [[33 38]
  [26 33]]

 [[29 36]
  [26 40]]

 [[78 44]
  [98 92]]

 [[38 74]
  [85 60]]

 [[15 64]
  [45  6]]

 [[57 19]
  [46 82]]

 [[26 95]
  [57 16]]

 [[41 12]
  [77 12]]

 [[86 74]
  [29 56]]

 [[86 51]
  [10 25]]

 [[65 34]
  [43 92]]

 [[18 96]
  [92 33]]

 [[32 61]
  [ 6 80]]

 [[96 37]
  [24 24]]

 [[21 84]
  [70 13]]

 [[35 36]
  [42  2]]

 [[73 35]
  [73 50]]

 [[59 35]
  [ 2 13]]

 [[61 81]
  [49 44]]]


In [38]:
# 9. Create a 3x3 array containing random numbers from (0, 1). Then, change the datatype of the array to integers
# (you need to do some googling for this).
# Ստեղծել 3x3 չափսի զանգված, որը կպարունակի 0-1 պատահական տվեր։ Ստեղծելուց հետո, փոխել զանգվածի արժեքների տիպը ամբողջ
# թվերի (պետք կլինի գուգլում փնտրել համապտասխան մեթոդը)։

In [39]:
arr = np.random.random((3,3))
print(arr)
print(arr.astype(int))
print(np.round(arr).astype(int))

[[0.25963644 0.96339756 0.37954355]
 [0.75008764 0.6055229  0.84094138]
 [0.19261641 0.22441967 0.2729646 ]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 1 0]
 [1 1 1]
 [0 0 0]]


In [40]:
# 10. Create two arrays of shape 3x3 that will contain random numbers from 1-100. Calculate their scalar product,
# dot product, division and difference. Use np methods AND corresponding operators.
# Ստեղծել երկու 3x3 զանգված։ Դրանք պետք է պարունակեն 1-100 պատահական թվեր։ Այնուհետև հաշվել դրանց սկալար արտադրյալը
# (համապտասխան տարրերն իրար հետ), վեկտորական արտադրյալը, քանորդը և տարբերությունը։ Օգտվել և՛ մեթոդներից և՛ համապատասխան
# օպերատորներից։

In [41]:
arr = np.random.randint(0,100,size=(3,3))
arr1 = np.random.randint(0,100,size=(3,3))

print(arr*arr1)
print(np.multiply(arr,arr1))
print('_'*45)
print(arr@arr1)
print(np.dot(arr,arr1))
print('_'*45)
print(arr/arr1)
print(np.divide(arr,arr1))
print('_'*45)
print(arr-arr1)
print(np.subtract(arr,arr1))

[[1725 1550 4800]
 [ 638 1037 3549]
 [1748  960 1728]]
[[1725 1550 4800]
 [ 638 1037 3549]
 [1748  960 1728]]
_____________________________________________
[[ 9725  4789 14366]
 [ 5655  2872 10215]
 [ 3563  1845  6584]]
[[ 9725  4789 14366]
 [ 5655  2872 10215]
 [ 3563  1845  6584]]
_____________________________________________
[[2.76       1.61290323 1.171875  ]
 [1.31818182 3.58823529 0.42857143]
 [0.20652174 1.66666667 0.33333333]]
[[2.76       1.61290323 1.171875  ]
 [1.31818182 3.58823529 0.42857143]
 [0.20652174 1.66666667 0.33333333]]
_____________________________________________
[[ 44  19  11]
 [  7  44 -52]
 [-73  16 -48]]
[[ 44  19  11]
 [  7  44 -52]
 [-73  16 -48]]


In [42]:
# 11. Create an array of shape 5x5. Calculate its determinant. If the determinant is non-zero, calculate the inverse as
# well. Otherwise, tell the user that the matrix in non-invertible.
# Ստեղծել 5x5 զանգված։ Հաշվել դրա որոշիչը։ Եթե այն 0 չէ, հաշվել մատրիցի հակադարձը։ Հակառակ դեպքում տպել, որ մատրիցը
# հակադարձելի չէ։

In [43]:
arr = np.random.randint(0,100,size=(5,5))

if np.linalg.det(arr) != 0:
    print(np.linalg.inv(arr))
else:
    print('Matrix is non-invertible')

[[-0.15024343 -0.1500897   0.0315715   0.12843422  0.10852604]
 [ 0.24021907  0.2582747  -0.06795082 -0.21194215 -0.15814814]
 [-0.10969804 -0.1226514   0.04153719  0.09545962  0.07474492]
 [-0.20753517 -0.21523241  0.0644735   0.18565842  0.12825234]
 [ 0.20727814  0.20541229 -0.05720416 -0.16997764 -0.13643487]]


In [44]:
# 12. Create an array of shape 3x3 that will contain numbers from 1-10. Calculate the scalar and dot products
# of it with its transposed version.
# Ստեղծել 1-10 թվերը պարունակող 3x3 զանգված։ Հաշվել դրա և իր տրանսպոնացված մատրիցի սկալար և վեկտորական արտադրյալները։

In [45]:
arr = np.arange(1,10).reshape(3,3)
arr_trans = arr.T

print(arr*arr_trans)
print(arr@arr_trans)

[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [46]:
# 13. Create a 3x3 array of random integers. Calculate its inverse (check if possible). Then find the vector product of
# these. What do you get?
# Ստեղծել պատահական ամբողջ թվեր պարունակող 3x3 զանգված։ Հաշվել դրա հակադարձը, եթե հնարավոր է (կրկին ստուգել որոշիչի
# պայմանը)։ Ապա հաշվել հակադարձի և օրիգինալ զանգվածների վեկտորական արտադրյալը։ Ի՞նչ կստանանք։

In [47]:
arr = np.random.randint(1,10, size=(3,3))

if np.linalg.det(arr) != 0:
    print(np.round(np.linalg.inv(arr)@arr).astype(int))
else:
    print('Matrix is non-invertible')

[[1 0 0]
 [0 1 0]
 [0 0 1]]
